FROM node:14 as base
WORKDIR /client
COPY /public ./public
COPY /src ./src
COPY /index.html ./
COPY /postcss* ./
COPY /tailwind* ./
COPY /tsconfig* ./
COPY /vite* ./
COPY /package.json ./
COPY /.env ./
RUN npm install

FROM base as build
RUN npm run build

FROM nginx:1.22 as development
COPY --from=build /client/dist/ /usr/share/nginx/html
COPY /nginx.config /etc/nginx/conf.d/default.conf
# CMD bash -c 'echo "Client running on http://localhost:3000"'