version: '3'

networks:
  app_network:

services:
  api:
    container_name: api
    image: api-dev
    restart: always
    build:
      context: ./backend/
      dockerfile: ./Dockerfile.api
      target: development
    ports:
      - '3030:3030'
    networks:
      - app_network
    command: bash -c "npm run dev"

  client:
    container_name: client
    image: client-dev
    restart: always
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile.client
      target: development
    ports:
      - '3000:82'
    depends_on:
      - api
    networks:
      - app_network